name: go toml-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Setup
        run: npm run setup
      - name: Install Packages
        run: npm install -f
      - name: Build
        run: npm run build
      - name: Install toml-test
        run: go install -v github.com/toml-lang/toml-test/cmd/toml-test@latest
      - name: Test
        run: run-toml-test.zsh
